training:
  learning_rate: 1e-5
  batch_size: 12
  epochs: 2
  optimizer: AdamW
  warmup_steps: 0.1  # 10% of total training steps
data:
  bitcoin_events_path: "/Users/hakeemshindy/Downloads/bitcoin_event.csv"  
  # Kaggle tweets (point at the folder containing your two CSVs)
  kaggle_dir: "/Users/hakeemshindy/Downloads/kaggle_tweet" 

  output_data_path: "/Users/hakeemshindy/Desktop/CryptoSentiment/CryptoSentiment_repo/data/output"  # Path to save processed data
  prebit_dataset_path: null  # Combined dataset from Kaggle

  prebit_dir: "/Users/hakeemshindy/Downloads/prebit_dir"  # Directory with yearly CSVs

  price_label_path:   "/Users/hakeemshindy/Downloads/btc_price/price_label.csv"

  rsi_threshold: [30, 70]
  roc_window_length: 8  # Assuming based on text
  preprocessing_steps:
    text_normalization: true
    remove_urls: true
    remove_user_ids: true
    remove_punctuation: true
    lemmatization: true
model:
  type: "CryptoBERT"           # CryptoBERT ≡ BERTweet maybe FinBERT
  pretrained_name: "vinai/bertweet-base"
  freeze_layers: 11            # freeze first 11 transformer blocks
  prompt_tuning: true
backtesting:
  using_library: "vectorbt"
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
signal_generation:
  methods:
    - majority
    - mean
market_labeling:
  strategy: "TBL_EWMA"  # Enhanced Triple Barrier Labeling with EWMA volatility
  barrier_window: 8-15  # Specified in paper
  upper_vol_mult: 1.0  # Volatility multiplier for upper barrier
  lower_vol_mult: 1.0  # Volatility multiplier for lower barrier
  # VOLATILITY MULTIPLIERS (not fixed percentages)
  # Barriers will be: Uₜ = Pₜ + Pₜ·σₜ·Fᵤ, Lₜ = Pₜ – Pₜ·σₜ·Fₗ
  fu_grid: [0.5, 1.0, 1.5, 2.0]   # Upper volatility multipliers
  fl_grid: [0.5, 1.0, 1.5, 2.0]   # Lower volatility multipliers  
  vt_grid: [3, 5, 7, 10]          # Vertical barrier horizons (days)
  rebalance_days: 126             # Re-optimize every 6 months
  
  # EWMA parameters
  ewma_tau: 30                    # 30-day EWMA decay parameter
  min_trend_days: 2               # Minimum days before allowing barrier hits
  roc_window: 8                   # ROC calculation window
  risk_free_rate: 0.04            # Annual risk-free rate for Sharpe calculation 